name: backend-ci
on: 
  pull_request:
    paths:
      - 'backend/**'
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend
    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: myButler
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MYBUTLER_GIT_TOKEN }}
          submodules: true
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build